# Generated by Django 3.0.1 on 2020-01-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costs', '0002_remove_costs_employee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekendCostsFlows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='流程名称')),
                ('desc', models.CharField(max_length=200, verbose_name='流程描述')),
                ('flow', models.CharField(max_length=200, verbose_name='流程内容')),
                ('step', models.IntegerField(default=0, verbose_name='当前流程状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('done_time', models.DateTimeField(verbose_name='完成时间')),
                ('costs', models.ManyToManyField(to='costs.Costs', verbose_name='账户')),
            ],
            options={
                'verbose_name': '周报流程',
                'verbose_name_plural': '周报流程',
            },
        ),
    ]
