# Generated by Django 3.0.1 on 2020-01-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempFlows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='流程名称')),
                ('desc', models.CharField(max_length=200, verbose_name='流程描述')),
                ('model', models.CharField(max_length=50, verbose_name='关联model')),
                ('data', models.CharField(max_length=1000, verbose_name='数据')),
                ('flow', models.CharField(max_length=200, verbose_name='流程内容')),
                ('step', models.IntegerField(default=0, verbose_name='当前流程状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('done_time', models.DateTimeField(verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '临时流程',
                'verbose_name_plural': '临时流程',
            },
        ),
    ]
