# Generated by Django 3.0.1 on 2020-01-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0002_tempflows'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempflows',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '流程中'), (1, '通过'), (2, '驳回')], default=0, verbose_name='流程状态'),
        ),
    ]
