# Generated by Django 3.0.1 on 2020-01-21 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField(verbose_name='出差日期')),
                ('location', models.CharField(default='重庆', max_length=30, verbose_name='出差地点')),
                ('work', models.CharField(max_length=100, verbose_name='工作内容')),
                ('trans_cost', models.FloatField(default=0, verbose_name='交通费')),
                ('hotel_cost', models.FloatField(default=0, verbose_name='住宿费')),
                ('local_trans_cost', models.FloatField(default=0, verbose_name='本地交通费')),
                ('meat_cost', models.FloatField(default=0, verbose_name='餐费')),
                ('local_car_cost', models.FloatField(default=0, verbose_name='本地租车费')),
                ('other_cost_1', models.FloatField(default=0, verbose_name='其他费用1')),
                ('other_cost_2', models.FloatField(default=0, verbose_name='其他费用2')),
                ('other_cost_3', models.FloatField(default=0, verbose_name='其他费用3')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='账户')),
                ('flows', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flows.WeekendCostsFlows', verbose_name='流程')),
            ],
            options={
                'verbose_name': '差旅成本',
                'verbose_name_plural': '差旅成本',
                'ordering': ['-travel_date'],
                'unique_together': {('account', 'travel_date')},
            },
        ),
    ]
