# Generated by Django 3.0.1 on 2020-01-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costs',
            name='flows',
        ),
    ]
