# Generated by Django 3.0.1 on 2020-01-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0003_costs_flows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='work',
            field=models.CharField(default='缺省', max_length=100, verbose_name='工作内容'),
        ),
    ]
