# Generated by Django 3.0.1 on 2020-02-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0004_auto_20200129_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='costs',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '正常'), (1, '修改中'), (2, '删除中')], default=0, verbose_name='状态'),
        ),
    ]
